apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web
  name: web-read
rules:
# web-dev user (View access for API resources, Edit access for Web resources).
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web
  name: web-edit
rules:
# web-dev user (View access for API resources, Edit access for Web resources).
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-web-edit-binding
  namespace: web
subjects:
- kind: User
  name: webdev@msftopenhack7166ops.onmicrosoft.com #web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: web-edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-api-read-binding
  namespace: web
subjects:
- kind: User
  name: apidev@msftopenhack7166ops.onmicrosoft.com #web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: web-read
  apiGroup: rbac.authorization.k8s.io