apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: poi
        image: dhacropenhack.azurecr.io/poi:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: CONFIG_FILES_PATH
          value: "/mnt/secrets-store"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name:  sql-credentials
              key:  username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  sql-credentials
              key:  password
        - name: SQL_SERVER
          valueFrom: 
            configMapKeyRef:
              name: configmap-database
              key: SQL_SERVER
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - port: 80
    targetPort: 80
    